const myArr=[0,1,2,3,4,5];
const arr2=new Array(1,2,3,4);
//console.log(myArr[0]);
myArr.push(6);
myArr.push(7);
myArr.pop();
myArr.unshift(8);
myArr.shift();
// console.log(myArr);
// console.log(myArr.includes(9));
// console.log(myArr.indexOf(6));
console.log("A",myArr);
let sl=myArr.slice(1,3);
console.log(sl);
console.log("B",myArr);
let sp=myArr.splice(1,3);
console.log(sp);
console.log("C",myArr);